### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by vladmihalcea** [liubo404/it-ebooks#1]
Hi,

I am Vlad Mihalcea, contacting you on behalf of Vlad Mihalcea, copyright holder of the works indicated below.

I believe that there is certain material available on your GitHub repository that infringes at least one of copyrights held by the above-mentioned party. 

enabling download of copyrighted work Vlad Mihalcea, description of which may be found here: https://leanpub.com/high-performance-java-persistence;

It is hereby requested that you remove or disable access to this materials as it appears on your service in as expedient fashion as possible.
I have a good faith belief that use of the material in the manner complained of is not authorized by the copyright holder, its agent, or the law and therefore I hereby request removal of the indicated copies.
Under penalty of perjury I certify that information in the notification is both true and accurate, and I am authorized to act on behalf of the holder of the right that is infringed.

Thank you for consideration,
Vlad Mihalcea

(My name written afore is to be considered my digital signature)

**Comment by DimaKazankov** [comment]
Hi,

I've removed.

**Comment by vladmihalcea** [comment]
You should remove them all. 

You're now violating copyright laws for lots of books from O'Reilley. Manning, and many more publishers.

**Comment by DimaKazankov** [comment]
I've removed all copies..
I haven't known I was violating copyright laws.

**Comment by vladmihalcea** [comment]
This is from [GitHub Terms of Service](https://help.github.com/articles/github-terms-of-service/):

> You may not use the Service for any illegal or unauthorized purpose. You must not, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright or trademark laws).

More, every book has  a Copyright section, and just because you can download these books from some obscure site or Torrent, it does not mean that it's legal. 

Both sharing and copying of copyright material [violates the DMCA law](https://en.wikipedia.org/wiki/Digital_Millennium_Copyright_Act). 

You should delete this GitHub repository.

**Comment by DimaKazankov** [comment]
![image](https://cloud.githubusercontent.com/assets/8181785/22777189/77d8c950-eec3-11e6-8268-ae7fbc2b165e.png)

**Comment by DimaKazankov** [comment]
Is it OK?

**Comment by vladmihalcea** [comment]
Before I close this issue, I want to explain one thing. 

This book took me 3 years to write, so I spent hundreds if hours so that you can benefit it. Also, the readers that buy it get updates for free, and there are going to be more updates to come. Paying an author means encouraging him to write more. Otherwise, I might just do consultancy and you won't benefit from my work. In the end, don't think about its price. Think about its value. 

Thank you.
